version: 2

ANCHORS:
  working_test: &working_test
    command: |
      set -x
      go build -o ibk main/main.go

      # Create test environement
      # All tests should be done in this directory
      mkdir test_env
      cd test_env

      # Create mydir and set up
      mkdir mydir
      echo "hello" > mydir/hello.txt
      mkdir mydir/dir1
      seq 9 > mydir/dir1/seq.txt

      # Backup
      ../ibk backup -b mybackup mydir

      # (I don't know why sleep is required)
      sleep 1

      # Modify a file
      seq 10 > mydir/dir1/seq.txt

      # Backup incrementally
      ../ibk backup -b mybackup mydir

      # Restore
      ../ibk restore -r myrestore mybackup

      # Check equality
      diff -r mydir/ myrestore/mydir/

jobs:
  linux_build:
    docker:
      - image: circleci/golang:1.11.0
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Working Test
          <<: *working_test
  
  macos_build:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          # NOTE: Should fix Go version
          name: Install Homebrew Dependencies
          command: brew install go gnu-tar
      - run:
          name: Show Environment
          command: |
            go version
      - run:
          name: Working Test
          <<: *working_test

workflows:
  version: 2
  builds:
    jobs:
      - linux_build
      - macos_build
